<a href="https://colab.research.google.com/github/raghavendra-1999/worklog/blob/master/Copy_of_17_06_20.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**SESSION(17-06-20)**

Steps involved in data pre-processing :
1. Importing Libraries
2. Importing the dataset
3. Missing Values
4. Categorical Data
5. Splitting Data
6. Feature Scaling

In [ ]:
import pandas as pd
import numpy as np
data = pd.read_csv("https://raw.githubusercontent.com/Mounika-Kajjam/Datasets/master/homeprices.csv ")
data

town  area   price
0   monroe township  2600  550000
1   monroe township  3000  565000
2   monroe township  3200  610000
3   monroe township  3600  680000
4   monroe township  4000  725000
5      west windsor  2600  585000
6      west windsor  2800  615000
7      west windsor  3300  650000
8      west windsor  3600  710000
9       robinsville  2600  575000
10      robinsville  2900  600000
11      robinsville  3100  620000
12      robinsville  3600  695000

Dummy variables using Sklearn Library
- LabelEncoder
- OnehotEncoder

In [ ]:
from sklearn.preprocessing import LabelEncoder
le  = LabelEncoder()

- We are creating dummies using Label encoader
- a class in sklearn
- obj is created and applied to data using fit.transform()

In [ ]:
# Creating copy of original data
price_data = data.copy()
price_data 

town  area   price
0   monroe township  2600  550000
1   monroe township  3000  565000
2   monroe township  3200  610000
3   monroe township  3600  680000
4   monroe township  4000  725000
5      west windsor  2600  585000
6      west windsor  2800  615000
7      west windsor  3300  650000
8      west windsor  3600  710000
9       robinsville  2600  575000
10      robinsville  2900  600000
11      robinsville  3100  620000
12      robinsville  3600  695000

In [ ]:
price_data.town = le.fit_transform(data.town)
price_data

town  area   price
0      0  2600  550000
1      0  3000  565000
2      0  3200  610000
3      0  3600  680000
4      0  4000  725000
5      2  2600  585000
6      2  2800  615000
7      2  3300  650000
8      2  3600  710000
9      1  2600  575000
10     1  2900  600000
11     1  3100  620000
12     1  3600  695000

**ONEHOTENCODER --> PD.GET_DUMMIES**

- import
- create obj
- Inside columntransfer we will pass onehotencoder
- manadatory arguments
 - (transforms,remainder)
 - transformers accepts a list of tuples

In [ ]:
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer

In [ ]:
#Insider the columntransfer we should pass onehotEncoder
column_trans = ColumnTransformer(transformers=[("encoder",OneHotEncoder(),[0])],remainder='passthrough')
# Pass through is to include non categorical colunms in data

In [ ]:
data = column_trans.fit_transform(data)
data  #with fit_transform we encode categorical variables

array([[0.00e+00, 1.00e+00, 0.00e+00, 0.00e+00, 2.60e+03, 5.50e+05],
       [0.00e+00, 1.00e+00, 0.00e+00, 0.00e+00, 3.00e+03, 5.65e+05],
       [0.00e+00, 1.00e+00, 0.00e+00, 0.00e+00, 3.20e+03, 6.10e+05],
       [0.00e+00, 1.00e+00, 0.00e+00, 0.00e+00, 3.60e+03, 6.80e+05],
       [0.00e+00, 1.00e+00, 0.00e+00, 0.00e+00, 4.00e+03, 7.25e+05],
       [1.00e+00, 0.00e+00, 0.00e+00, 1.00e+00, 2.60e+03, 5.85e+05],
       [1.00e+00, 0.00e+00, 0.00e+00, 1.00e+00, 2.80e+03, 6.15e+05],
       [1.00e+00, 0.00e+00, 0.00e+00, 1.00e+00, 3.30e+03, 6.50e+05],
       [1.00e+00, 0.00e+00, 0.00e+00, 1.00e+00, 3.60e+03, 7.10e+05],
       [1.00e+00, 0.00e+00, 1.00e+00, 0.00e+00, 2.60e+03, 5.75e+05],
       [1.00e+00, 0.00e+00, 1.00e+00, 0.00e+00, 2.90e+03, 6.00e+05],
       [1.00e+00, 0.00e+00, 1.00e+00, 0.00e+00, 3.10e+03, 6.20e+05],
       [1.00e+00, 0.00e+00, 1.00e+00, 0.00e+00, 3.60e+03, 6.95e+05]])

In [ ]:
# Array is returned we need to convert into df
x = pd.DataFrame(data)
x

0    1    2    3       4         5
0   0.0  1.0  0.0  0.0  2600.0  550000.0
1   0.0  1.0  0.0  0.0  3000.0  565000.0
2   0.0  1.0  0.0  0.0  3200.0  610000.0
3   0.0  1.0  0.0  0.0  3600.0  680000.0
4   0.0  1.0  0.0  0.0  4000.0  725000.0
5   1.0  0.0  0.0  1.0  2600.0  585000.0
6   1.0  0.0  0.0  1.0  2800.0  615000.0
7   1.0  0.0  0.0  1.0  3300.0  650000.0
8   1.0  0.0  0.0  1.0  3600.0  710000.0
9   1.0  0.0  1.0  0.0  2600.0  575000.0
10  1.0  0.0  1.0  0.0  2900.0  600000.0
11  1.0  0.0  1.0  0.0  3100.0  620000.0
12  1.0  0.0  1.0  0.0  3600.0  695000.0

**Splitting the data set**
- Input and output are splited

In [ ]:
# input in caps and output in small
# before executing this data is read again since data is converted to array
X = data.iloc[:,0:2] #(town ,area)-->i/p
X

town  area
0   monroe township  2600
1   monroe township  3000
2   monroe township  3200
3   monroe township  3600
4   monroe township  4000
5      west windsor  2600
6      west windsor  2800
7      west windsor  3300
8      west windsor  3600
9       robinsville  2600
10      robinsville  2900
11      robinsville  3100
12      robinsville  3600

In [ ]:
#output
y = data.price
y

0     550000
1     565000
2     610000
3     680000
4     725000
5     585000
6     615000
7     650000
8     710000
9     575000
10    600000
11    620000
12    695000
Name: price, dtype: int64

- Split input and output into training and testing

In [ ]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2,random_state=1)
#20 % are taken for testing
#random state freezes out testing data

In [ ]:
print(X_train.shape) #i/p train
print(X_test.shape)  #i/p test
print(y_train.shape) #o/p train
print(y_test.shape)  #o/p test

(10, 2)
(3, 2)
(10,)
(3,)


In [ ]:
X_train
# though u run for n no of times it does not chnage due to random stae

town  area
10      robinsville  2900
1   monroe township  3000
6      west windsor  2800
0   monroe township  2600
7      west windsor  3300
12      robinsville  3600
9       robinsville  2600
8      west windsor  3600
11      robinsville  3100
5      west windsor  2600

**FEATURE SCALING**(OPTIONAL)

In [ ]:
sample = pd.DataFrame({"w.e":[2,4,5,6,7,8],"age":[28,25,32,45,33,32],"sal":[30000,34000,67000,56000,64000,56000],"dis":[10,20,30,45,67,89],"expected sal":[100000,100000,100000,100000,100000,100000]})
sample

w.e  age    sal  dis  expected sal
0    2   28  30000   10        100000
1    4   25  34000   20        100000
2    5   32  67000   30        100000
3    6   45  56000   45        100000
4    7   33  64000   67        100000
5    8   32  56000   89        100000

- Most ml algorithms we use distance based formulae
- All columns have diff magnitude 
- When feature scaling magnitudes are removed ab=nd coverted to same scale without any units or scaleless

In [ ]:
from sklearn.preprocessing import scale
scale_data = scale(sample)
scale_data


array([[-1.69030851, -0.72134777, -1.49370422, -1.22576928,  0.        ],
       [-0.6761234 , -1.20224629, -1.21142941, -0.859868  ,  0.        ],
       [-0.16903085, -0.08014975,  1.1173378 , -0.49396672,  0.        ],
       [ 0.3380617 ,  2.00374382,  0.34108207,  0.05488519,  0.        ],
       [ 0.84515425,  0.08014975,  0.90563169,  0.859868  ,  0.        ],
       [ 1.35224681, -0.08014975,  0.34108207,  1.66485081,  0.        ]])

In [ ]:
scale_data = pd.DataFrame(scale_data)
scale_data

0         1         2         3    4
0 -1.690309 -0.721348 -1.493704 -1.225769  0.0
1 -0.676123 -1.202246 -1.211429 -0.859868  0.0
2 -0.169031 -0.080150  1.117338 -0.493967  0.0
3  0.338062  2.003744  0.341082  0.054885  0.0
4  0.845154  0.080150  0.905632  0.859868  0.0
5  1.352247 -0.080150  0.341082  1.664851  0.0

In [ ]:
std = sample.copy()
std

w.e  age    sal  dis  expected sal
0    2   28  30000   10        100000
1    4   25  34000   20        100000
2    5   32  67000   30        100000
3    6   45  56000   45        100000
4    7   33  64000   67        100000
5    8   32  56000   89        100000

Using StandardScalar

In [ ]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
std = sc.fit_transform(std)
std
#compress mean of any column to 0 stdscaler

array([[-1.69030851, -0.72134777, -1.49370422, -1.22576928,  0.        ],
       [-0.6761234 , -1.20224629, -1.21142941, -0.859868  ,  0.        ],
       [-0.16903085, -0.08014975,  1.1173378 , -0.49396672,  0.        ],
       [ 0.3380617 ,  2.00374382,  0.34108207,  0.05488519,  0.        ],
       [ 0.84515425,  0.08014975,  0.90563169,  0.859868  ,  0.        ],
       [ 1.35224681, -0.08014975,  0.34108207,  1.66485081,  0.        ]])

In [ ]:
std= pd.DataFrame(std)
std

0         1         2         3    4
0 -1.690309 -0.721348 -1.493704 -1.225769  0.0
1 -0.676123 -1.202246 -1.211429 -0.859868  0.0
2 -0.169031 -0.080150  1.117338 -0.493967  0.0
3  0.338062  2.003744  0.341082  0.054885  0.0
4  0.845154  0.080150  0.905632  0.859868  0.0
5  1.352247 -0.080150  0.341082  1.664851  0.0

**MIN MAX scaler**

In [ ]:
from sklearn.preprocessing import MinMaxScaler
mn = MinMaxScaler()
mn.fit(sample)
sample = mn.transform(sample)
sample
#It will get all vales in range(0,1) if -ve value then [-1,1]

array([[0.        , 0.15      , 0.        , 0.        , 0.        ],
       [0.33333333, 0.        , 0.10810811, 0.12658228, 0.        ],
       [0.5       , 0.35      , 1.        , 0.25316456, 0.        ],
       [0.66666667, 1.        , 0.7027027 , 0.44303797, 0.        ],
       [0.83333333, 0.4       , 0.91891892, 0.72151899, 0.        ],
       [1.        , 0.35      , 0.7027027 , 1.        , 0.        ]])